
# Give the path to the folder containing all input files 
in_folder: "/sc/arion/projects/bigbrain/data/genotypes/BipSeq/vcfs/imputed_genotypes/1M/job-20211015-201944-526-BipSeq_1M/local/"

# Specify the file type of your inputs. Can be 'vcf' or 'plink'
input_type: "vcf" 

# Path to the output folder where QCed data files will be written
out_folder: "/sc/arion/projects/bigbrain/data/genotypes/BipSeq/vcfs/QCed_genotypes/1M/"

# Name of your data - the output files generated will be named <data_name>_hg38_all_chr.vcf.gz
data_name: "BipSeq_1M"

# Do you want to keep the intermediate files? It can be helpful for debugging
# They do take up a lot of storage though. 0 = No; 1 = Yes. 
# We suggest keep files only on small test data.
keep_intermediate: 1

# Filter Thresholds:
# Missingness
miss_SNP: 0.02
miss_ind: 0.02

# Minor Allele Frequency
MAF: 0.01

# Hardy Weinberg
hwe_step1: 1e-6
hwe_step2: 1e-6

